version: 2

models:
  - name: stg_ga4_events
    columns:
      - name: user_id
        tests: [not_null]
      - name: event_name
        tests:
          - not_null
          - accepted_values:
              values: ['signup', 'start_trial', 'purchase']
